### PR TITLE
PR to allow for Headers in config json

### PR DESCRIPTION
**Pull request by waelchatila**
Also adding some convenient makefile targets

### CODE REVIEW

**Comment by waelchatila** [comment]
1. there is a unit test which echos supplied headers back to the caller (see requestor_test)
2. manual verification by standing up a local server and printing headers as they come in from heyyall

**Comment by youngkin** [comment]
Would you be interested in taking over ownership of this? I'm no longer doing software development and it probably doesn't make sense for me to own this.

**Comment by waelchatila** [comment]
thanks for the offer, but no, not interested : ).

**Review by youngkin — COMMENTED** [review]
Approved

**Pull request merged**
